### ISSUE TITLE
Made Back-End for To-Do

### ISSUE THREAD

**Issue by McMuffin1022** [McMuffin1022/ToDoApp#6]
- [ ] Do BD Schema
- [ ] Create my models
- [ ] Connect to my front-end
- [ ] Di a responsive and usefull UI
